---

- name: "Copy {{ odbc_openrda_pkg }} to temp directory"
  win_copy:
    src: "{{ odbc_openrda_src }}{{ odbc_openrda_pkg }}"
    dest: "{{ ansible_env['TMP'] }}\\"

- name: Unzip the {{ odbc_openrda_pkg }}
  win_unzip:
    src: "{{ ansible_env['TMP'] }}\\{{ odbc_openrda_pkg }}"
    dest: "{{ ansible_env['TMP'] }}\\OpenRDA"

- name: "Move OpenRDA files into {{ odbc_openrda_dest }}"
  win_robocopy:
    src: "{{ ansible_env['TMP'] }}\\OpenRDA\\OpenRDA\\"
    dest: "{{ odbc_openrda_dest }}"
    flags: /MIR /MOVE

- name: "Create shortcut to odbcisql.exe"
  win_shortcut:
    src: "{{ odbc_openrda_dest }}\\DNA\\SQLEngine\\3rdParty\\ATI\\bin\\iwinnt\\odbcisql.exe"
    dest: "{{ ansible_env['PUBLIC'] }}\\Desktop\\OpenRDA Interactive SQL (x64).lnk"
    directory: "{{ ansible_env['windir'] }}\\system32"

- name: "Register the OpenRDA ODBC driver"
  block:
    - win_regedit:
        path: HKLM:\SOFTWARE\ODBC\ODBCINST.INI\OpenRDA
        name: Driver
        data: "{{ odbc_openrda_dest }}DNA\\SQLEngine\\3rdParty\\ATI\\bin\\iwinnt\\oaodbc32.dll"
    - win_regedit:
        path: HKLM:\SOFTWARE\ODBC\ODBCINST.INI\OpenRDA
        name: setup
        data: "{{ odbc_openrda_dest }}DNA\\SQLEngine\\3rdParty\\ATI\\bin\\iwinnt\\oastp32.dll"
    - win_regedit:
        path: HKLM:\SOFTWARE\ODBC\ODBCINST.INI\OpenRDA
        name: CustomPropertiesSetup
        data: ""
    - win_regedit:
        path: HKLM:\SOFTWARE\ODBC\ODBCINST.INI\ODBC Drivers
        name: OpenRDA
        data: Installed

- name: "Configure the OpenRDA ODBC driver"
  template:
    src: templates/openrda.ini.j2
    dest: "{{ odbc_openrda_dest }}DNA\\SQLEngine\\3rdParty\\ATI\\bin\\iwinnt\\openrda.ini"
    newline_sequence: '\r\n'

- name: "Configure the OpenAccess Database (oadrd.ini)"
  win_file:
    path: "{{ odbc_openrda_dest }}DNA\\SQLEngine\\3rdParty\\ATI\\schema\\oadrd.ini"
    state: touch

- name: "Configure the OpenAccess Database (add DBs)"
  include_tasks: add-db.yml
  with_items:
    "{{ odbc_openrda_dbs }}"

- name: "Configure the OpenAccess Database (cleanup)"
  win_file:
    path: "{{ odbc_openrda_dest }}DNA\\SQLEngine\\3rdParty\\ATI\\schema\\oadrd_.ini"
    state: absent

- name: "Configure the OpenAccess Database Sources"
  include_tasks: add-db-sources.yml
  with_items:
    "{{ odbc_openrda_data_sources }}"
