---

- name: "Copy {{ odbc_openrda_pkg }} to temp directory"
  win_copy:
    src: "{{ odbc_openrda_src }}{{ odbc_openrda_pkg }}"
    dest: "{{ ansible_env['TMP'] }}"

- name: Unzip the {{ odbc_openrda_pkg }}
  win_unzip:
    src: "{{ ansible_env['TMP'] }}\\{{ odbc_openrda_pkg }}"
    dest: "{{ ansible_env['TMP'] }}\\OpenRDA"

- name: "Move OpenRDA files into {{ odbc_openrda_dest }}"
  win_robocopy:
    src: "{{ ansible_env['TMP'] }}\\OpenRDA\\OpenRDA\\"
    dest: "{{ odbc_openrda_dest }}"
    flags: /MIR /MOVE

- name: "Create shortcut to odbcisql.exe"
  win_shortcut:
    src: "{{ odbc_openrda_dest }}\\DNA\\SQLEngine\\3rdParty\\ATI\\bin\\iwinnt\\odbcisql.exe"
    dest: "{{ ansible_env['PUBLIC'] }}\\Desktop\\OpenRDA Interactive SQL (x64).lnk"
    directory: "{{ ansible_env['windir'] }}\\system32"
