---

- name: "Copy {{ odbc_openrda_pkg }} to temp directory"
  win_copy:
    src: "{{ odbc_openrda_src }}{{ odbc_openrda_pkg }}"
    dest: "{{ ansible_env['TMP'] }}"

- name: Unzip the {{ odbc_openrda_pkg }}
  win_unzip:
    src: "{{ ansible_env['TMP'] }}\\{{ odbc_openrda_pkg }}"
    dest: "{{ ansible_env['TMP'] }}\\OpenRDA"
